name = "DOM Grill"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = "Some tooltip?"; // tool tip on mouse hover
overview = "Some first mod overview"; // overview
action = "https://dayz.com/"; // link
author = "SHoover80, GickiAnarchy"; // author
version = "1.0"; // version
